pytorque/urls.py
from django.conf.urls.defaults import *

urlpatterns = patterns('pytorque.views',
    (r'^$', 'central_dispatch_view'),
    (r'^browse$', 'central_dispatch_view'),
    (r'^monitor$', 'central_dispatch_view'),
    (r'^submit$', 'central_dispatch_view'),
    (r'^stat$', 'central_dispatch_view'),

    (r'^login/$', 'login'),
    (r'^logout/$', 'logout'),

#    (r'^$', 'central_dispatch_view'),
    (r'^user/(?P<username>\w{0,50})/$', 'index'),
    (r'^user/(?P<username>\w{0,50})/browse$', 'browse'),
#    (r'^user/(?P<username>\w{0,50})/monitor', 'monitor'),
#    (r'^user/(?P<username>\w{0,50})/submit', 'submit'),
#    (r'^user/(?P<username>\w{0,50})/stat', 'stat'),
)
  

urls.py
from django.conf.urls.defaults import patterns, include, url

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
import settings

admin.autodiscover()

urlpatterns = patterns('',
    #    url(r'^$', redirect_to, {'url': '/pytorque/'}),

    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^admin/', include(admin.site.urls)),
    (r'^favicon\.ico$', 'django.views.generic.simple.redirect_to', {'url': '/media/images/favicon.ico'}),
    (r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT, 'show_indexes': True})
    ,

    #    url(r'^pytorque/', include('pytorque.urls')),


    (r'^$', 'pytorque.views.central_dispatch_view'),
    (r'^browse$', 'pytorque.views.central_dispatch_view'),
    (r'^monitor$', 'pytorque.views.central_dispatch_view'),
    (r'^submit$', 'pytorque.views.central_dispatch_view'),
    (r'^stat$', 'pytorque.views.central_dispatch_view'),

    (r'^login/$', 'pytorque.views.login'),
    (r'^logout/$', 'pytorque.views.logout'),

    (r'^user/(?P<username>\w{0,50})/$', 'pytorque.views.index'),
    (r'^user/(?P<username>\w{0,50})/browse$', 'pytorque.views.browse'),
    (r'^user/(?P<username>\w{0,50})/browse/get_children$', 'pytorque.views.get_children'),
    (r'^user/(?P<username>\w{0,50})/browse/upload$', 'pytorque.views.fileUpload'),
    (r'^user/(?P<username>\w{0,50})/browse/download$', 'pytorque.views.fileDownload'),
    (r'^user/(?P<username>\w{0,50})/browse/remove$', 'pytorque.views.fileRemove'),
    (r'^user/(?P<username>\w{0,50})/monitor$', 'pytorque.views.monitor'),
    (r'^user/(?P<username>\w{0,50})/monitor/get_jobs$', 'pytorque.views.get_jobs'),
    (r'^user/(?P<username>\w{0,50})/submit$', 'pytorque.views.submit'),
    (r'^user/(?P<username>\w{0,50})/stat$', 'pytorque.views.stat'),
)

pytorque/forms.py
from django.core.exceptions import ValidationError
from django.core.validators import RegexValidator, MaxLengthValidator

__author__ = 'rauch'

from django import forms

class UploadFileForm(forms.Form):
    file = forms.FileField()


def validate_job_name(job_name):
    if job_name.find(" ") >= 0:
        raise ValidationError(
            u'The name specified may be up to and including 15 characters in length.  It must consist of  printable,  non  white space characters with the first character alphabetic.')


class SubmitScriptForm(forms.Form):
    def __init__(self, *args, **kwargs):
        super(SubmitScriptForm, self).__init__(*args, **kwargs)
        self.fields['stageInFrom'].widget.attrs['readonly'] = True
        self.fields['stageInTo'].widget.attrs['readonly'] = True
        self.fields['stageOutFrom'].widget.attrs['readonly'] = True
        self.fields['stageOutTo'].widget.attrs['readonly'] = True

    #    def __init__(self, queues_choices):
    #        self.queues_choices = queues_choices
    #        super(SubmitScriptForm, self).__init__()
    #
    #    def __init__(self, postData, queues_choices):
    #        self.queues_choices = queues_choices
    #        super(SubmitScriptForm, self).__init__(postData)

    #    hardcoded queues codes
    #    class Meta:
    #        model = SubmitScript


    QUEUES_CHOICES = (('batch', 'batch'), ('custom', 'custom'))
    CPU_CNT_CHOICES = (('1', '1'), ('2', '2'), ('3','3'), ('4', '4'))

    #Job Name
    jobName = forms.CharField(validators=[RegexValidator, MaxLengthValidator, validate_job_name], initial='new_job',
        label='Job name',
        max_length=15, error_messages={
            'max_length': 'The name specified may be up to and including 15 characters in length.  It must consist of  printable,  non  white space characters with the first character alphabetic.'})


    #Job Options
    #todo: get it from Model
    queueToSubmitJobTo = forms.ChoiceField(label='Queue to submit job to:', choices=QUEUES_CHOICES, initial='batch')

    cpuToUse = forms.ChoiceField(label='Number of\n processors to use:', choices=CPU_CNT_CHOICES, initial='1')

    maxTime = forms.TimeField(label='Maximum time\n(HH:MM:SS)', initial='01:00:00')
    sendMessageAbort = forms.BooleanField(label='Aborts', initial=False, required=False)
    sendMessageEnd = forms.BooleanField(label='Ends', initial=False, required=False)
    sendMessageStart = forms.BooleanField(label='Starts', initial=False, required=False)
    sendMessageTo = forms.EmailField(label='Address to send message to:', help_text='info@example.com', required=False,
        initial='info@example.com')

    #Execution Commands
    executionCommands = forms.CharField(label='Execution commands:', required=False, widget=forms.Textarea,
        initial='echo "Hello world"\npwd\ndate\nsleep 301\ndate\necho "Done"')

    #File Staging
    stageInFrom = forms.URLField(label='From here:', required=False)
    stageInTo = forms.URLField(label='To there:', required=False)
    stageOutFrom = forms.URLField(label='From here:', required=False)
    stageOutTo = forms.URLField(label='To there:', required=False)

pytorque/views.py
from datetime import datetime, timedelta
import os
import string
import urlparse
from django.core.servers.basehttp import FileWrapper
from django.utils.translation import ugettext as _
from django.contrib.auth import REDIRECT_FIELD_NAME, login as auth_login, logout as auth_logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.sites.models import get_current_site
from django.http import  HttpResponseRedirect, HttpResponseForbidden, HttpResponseNotFound, HttpResponse
from django.shortcuts import render_to_response
from django.template import RequestContext
import getpass
import logging
from django.views.decorators.cache import never_cache
from django.views.decorators.csrf import csrf_protect
import jsonpickle
import time
from pytorque import strings
from pytorque.forms import UploadFileForm, SubmitScriptForm
from pytorque.libs.charts import ChartGenerator
from pytorque.libs.file_node import FileNode
from pytorque.libs.torque_service import TorqueService
from pytorque.libs.upload_handler import UploadHandler
from pytorque.models import FileObject

import settings

server_logger = logging.getLogger('pytorque.custom')

ROOT_URL = "/"


def is_allowed_user(orig_func):
    def _decorated(request, username=None):
        if username:
            if request.user.username == username:
                return orig_func(request, username)
            else:
                return HttpResponseForbidden()
        else:
            return HttpResponseNotFound()

    return _decorated


@login_required
@is_allowed_user
def index(request, username=None):
    return render_to_response('pytorque/index.html',
        RequestContext(request, {'userName': username, 'py_userName': getpass.getuser()}))


def central_dispatch_view(request):
    if request.user and request.user.is_authenticated():
        requestedPath = request.get_full_path()
        return HttpResponseRedirect(ROOT_URL + "user/" + request.user.username + requestedPath)
    else:
        return HttpResponseRedirect(ROOT_URL + "login/")


@csrf_protect
@never_cache
def login(request, template_name='registration/login_reg.html',
          redirect_field_name=REDIRECT_FIELD_NAME,
          authentication_form=AuthenticationForm,
          current_app=None, extra_context=None):
    """
    Displays the login form and handles the login action.
    """
    redirect_to = request.REQUEST.get(redirect_field_name, '')

    if request.method == "POST":
        form = authentication_form(data=request.POST)
        if form.is_valid():
            netloc = urlparse.urlparse(redirect_to)[1]

            # Use default setting if redirect_to is empty
            if not redirect_to:
                redirect_to = settings.LOGIN_REDIRECT_URL

            # Security check -- don't allow redirection to a different
            # host.
            elif netloc and netloc != request.get_host():
                redirect_to = settings.LOGIN_REDIRECT_URL

            # Okay, security checks complete. Log the user in.
            auth_login(request, form.get_user())

            if request.session.test_cookie_worked():
                request.session.delete_test_cookie()

            request.session['userPWD'] = form.cleaned_data['password']

            return HttpResponseRedirect(redirect_to)
    else:
        form = authentication_form(request)

    request.session.set_test_cookie()

    current_site = get_current_site(request)

    context = {
        'form': form,
        redirect_field_name: redirect_to,
        'site': current_site,
        'site_name': current_site.name,
        }
    context.update(extra_context or {})
    return render_to_response(template_name, context,
        context_instance=RequestContext(request, current_app=current_app))


def logout(request, next_page=None,
           template_name='registration/logged_out_reg.html',
           redirect_field_name=REDIRECT_FIELD_NAME,
           current_app=None, extra_context=None):
    """
    Logs out the user and displays 'You are logged out' message.
    """
    auth_logout(request)
    redirect_to = request.REQUEST.get(redirect_field_name, '')
    if redirect_to:
        netloc = urlparse.urlparse(redirect_to)[1]
        # Security check -- don't allow redirection to a different host.
        if not (netloc and netloc != request.get_host()):
            return HttpResponseRedirect(redirect_to)

    if next_page is None:
        current_site = get_current_site(request)
        context = {
            'site': current_site,
            'site_name': current_site.name,
            'title': _('Logged out')
        }
        context.update(extra_context or {})
        return render_to_response(template_name, context,
            context_instance=RequestContext(request, current_app=current_app))
    else:
        # Redirect to this page until the session has been cleared.
        return HttpResponseRedirect(next_page or request.path)


@login_required
@is_allowed_user
def browse(request, username=None):
    return render_to_response('pytorque/browse.html',
        RequestContext(request, {'userName': username, 'py_userName': getpass.getuser()}))


@login_required
@is_allowed_user
def get_children(request, username=None):
    resultJSON = {}

    if request.method == 'GET':
        selectedNodeId = request.GET.get('id')
        if selectedNodeId:
            nodeId = selectedNodeId
        else:
            nodeId = "/home/" + username

        try:
            fileNode = FileNode.createDirectoryNode(nodeId)
            resultJSON = jsonpickle.encode(fileNode, unpicklable=False)
        except Exception as exc:
            server_logger.error(exc)

    return HttpResponse(resultJSON, content_type="application/json")


@login_required
@is_allowed_user
def fileUpload(request, username=None):
    errorMessage = ''
    if request.method == 'POST':
        form = UploadFileForm(request.POST, request.FILES)
        destinationPath = request.POST.get('currentDirectory')
        if form.is_valid() and destinationPath:
            uploadedFile = request.FILES['file']

            server_logger.info("User '%s' is trying to upload file: %s" % (username, uploadedFile.name))
            try:
                UploadHandler.handle(destinationPath, uploadedFile)

                #                userFile = FileObject(user = request.user, file_name = os.path.join(destinationPath, uploadedFile.name))
                #                userFile.save()

                FileObject.objects.create(user=request.user, file_name=os.path.join(destinationPath, uploadedFile.name))
            except Exception as exc:
                server_logger.error(
                    strings.STR_HANDLE_FILE_EXCEPTION_MSG % ('uploading file: ' + uploadedFile.name, str(exc)))
                errorMessage = str(exc)

            return HttpResponseRedirect('/user/' + username + '/browse')

        else:
            form = UploadFileForm()
    else:
        form = UploadFileForm()
    return render_to_response('pytorque/upload.html', RequestContext(request, {'userName': username, 'form': form,
                                                                               'currentDirectory': destinationPath,
                                                                               'errorMessage': errorMessage}))


@login_required
@is_allowed_user
def fileDownload(request, username=None):
    errorMessage = ''
    if request.method == 'POST':
        fileName = request.POST.get('currentFile')
        server_logger.info("User '%s' is trying to download file: %s" % (username, fileName))

        try:
            fileToSend = file(fileName, 'r')

            wrapper = FileWrapper(fileToSend)
            response = HttpResponse(wrapper, content_type="application/force-download")
            response['Content-Length'] = os.path.getsize(fileName)
            response['Content-Disposition'] = 'attachment; filename=' + fileToSend.name.encode('utf8')
            return response
        except Exception as exc:
            server_logger.error(strings.STR_IO_EXCEPTION_MSG % ("opening file " + fileName, str(exc)))
            errorMessage = str(exc)

    return render_to_response('pytorque/browse.html', RequestContext(request, {'userName': username,
                                                                               'errorMessage': errorMessage}))


@login_required
@is_allowed_user
def fileRemove(request, username=None):
    resultDict = {"status": "success", "message": ""}

    if request.POST:
        itemToRemove = request.POST.get('id')
        server_logger.info("User '%s' is trying to remove file: %s" % (username, itemToRemove))

        if itemToRemove:
            if os.path.isfile(itemToRemove):
                try:
                    os.remove(itemToRemove)
                    resultDict["status"] = "success"
                except Exception as exc:
                    server_logger.error(strings.STR_HANDLE_FILE_EXCEPTION_MSG % ('removing file', str(exc)))
                    resultDict["status"] = "error"
                    resultDict["message"] = (strings.STR_HANDLE_FILE_EXCEPTION_MSG % ('removing file', str(exc)))
            else:
                resultDict["status"] = "error"
                resultDict["message"] = "File could be removed only"
        else:
            resultDict["status"] = "error"
            resultDict["message"] = "Item to remove must be selected"
    else:
        resultDict["status"] = "error"
        resultDict["message"] = "Please, use `post` request"

    resultJSON = jsonpickle.encode(resultDict)
    return HttpResponse(resultJSON, content_type="application/json")


@login_required
@is_allowed_user
def monitor(request, username=None):
    return render_to_response('pytorque/monitor.html',
        RequestContext(request, {'userName': username}))


@login_required
@is_allowed_user
def get_jobs(request, username=None):
    resultJSON = {}

templates/pytorque/base.html
{% load i18n %}
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
    <link type="text/css" rel="stylesheet" media="all" href="/media/css/styles.css"/>
    {#    <link type="text/css" rel="stylesheet" href="/media/css/treegrid.css"/>#}
    <link type="text/css" rel="stylesheet" href="/media/jtable_themes/themes/lightcolor/gray/jtable.css"/>
    <link type="text/css" rel="stylesheet" href="/media/css/jquery-ui-1.8.18.custom.css"/>

    <script src="/media/js/jquery-1.7.2.min.js" type="text/javascript"></script>
    <script src="/media/js/jquery.jstree.js" type="text/javascript"></script>
    <script src="/media/js/jstreegrid.js" type="text/javascript"></script>
    <script src="/media/js/jquery-ui-1.8.18.custom.min.js" type="text/javascript"></script>
    <script src="/media/js/jquery.jtable.js" type="text/javascript"></script>
    <script src="/media/js/lavalamp.js" type="text/javascript"></script>
    <script src="/media/js/commonFunctions.js" type="text/javascript"></script>
    {% block header %}
        <title>{% block title %}PyTorque{% endblock %}</title>
        {% block additionalHeadContent %}{% endblock %}
    {% endblock %}
    {% block blockbots %}<meta name="robots" content="NONE,NOARCHIVE" />{% endblock %}
    <meta name="google-site-verification" content="AoP7eFD74iQDawvS1-2gMP0Wvii13AxYz7rDwfNLjcs" />
</head>

<body>
<!-- Container -->
<div id="container">
    <!-- main_panel -->
    <div id="header" class="center outer_block">
        <div class="lavalamp">
            <ul>
                <li class="active"><a href="/">Home</a></li>
                <li><a href="/browse">Browse home directory</a></li>
                <li><a href="/monitor">Monitoring</a></li>
                <li><a href="/submit">Submition</a></li>
                <li><a href="/stat">Statistics</a></li>
                <!-- Authentication -->
                <div id="authentication">
                    {% block login %}
                        {% if user.is_authenticated %}
                            <pre>{% trans "Welcome " %}, <strong>{{ user.username }}</strong>. <a
                                    href="/logout/">logout</a> / <a
                                    href="/admin/">admin</a> </pre>
                        {% else %}
                            <pre>Welcome, new user. <a href="/login/">login</a> / <a href="/admin/">admin</a> </pre>
                        {% endif %}
                    {% endblock %}
                </div>
            </ul>
            <div class="floatr"></div>
        </div>
    </div>

    <!-- body -->
    <div id="body" class="center outer_block">
        <!-- Content -->
        <div id="content">
            {% block content %}{% endblock %}

            <script type="text/javascript">
                $(document).ready(function () {
                    var errMsg = "{{ errorMessage }}";
                    if (errMsg) {
                        showError(errMsg)
                    }

                    var infMsg = "{{ infoMessage }}";
                    if (infMsg) {
                        showInfo(infMsg)
                    }
                });
            </script>

            <div class="notification info">Info message</div>
            <div class="notification success">Successful operation message</div>
            <div class="notification warning">Warning message</div>
            <div class="notification error">Error message</div>
        </div>
        <!-- END Content -->
    </div>
</div>
</body>
</html>

templates/pytorque/index.html
{% extends "pytorque/base.html" %}

{% load i18n %}

{% block title %}
    PyTorque
{% endblock %}

{% block content %}

    <div class="center">
        <br>
        Welcome to PyTorque, service which exposes an interface for an open source distributed resource manager PBS Torque
        <br><br>
        <b>With the service you are able to:</b>
        <ul>
            <li>get access to your home directory</li>
            <li>easy manage files in the home directory</li>
            <li>submit your own jobs to PBS torque server with equal ease</li>
            <li>manage jobs without logging into any remote machines. The user may view jobs in queues and delete any of their currently queued or running jobs.</li>
            <li>monitor queues status</li>
            <li>do all of this in a secure manner (via SSL)</li>
        </ul>
    </div>

{% endblock %}

templates/pytorque/monitor.html
{% extends "pytorque/base.html" %}

{% block title %}
    PyTorque monitoring
{% endblock %}

{% block content %}
    <script type="text/javascript">
        $(document).ready(function () {
            $('#JobsContainer').jtable({
                title:'Jobs',
                openChildAsAccordion:true,
                defaultDateFormat:'dd-mm-yy',
                defaultSorting:'Name DESC',
                selecting:true,
//                selectingCheckboxes:true,
                sorting:false,

                actions:{
                    listAction:"{{ "/user/"|add:userName|add:"/monitor/get_jobs"}}",
                    createAction:"{{ "/user/"|add:userName|add:"/monitor/create_job"}}",
                    updateAction:"{{ "/user/"|add:userName|add:"/monitor/update_job"}}",
                    deleteAction:"{{ "/user/"|add:userName|add:"/monitor/delete_job"}}"
                },
                fields:{
                    jobId:{
                        key:true,
                        title:'Job Id',
                        width:'9%',
                        create:false,
                        edit:false,
                        list:true
                    },
                    state:{
                        title:'State',
                        width:'3%'
                    },
                    user:{
                        title:'User',
                        width:'12%',
                        create:false,
                        edit:true,
                        input:function (data) {
                            if (data.record) {
                                return '<input type="text" style="width:200px" value="' + data.record.user + '" />';
                            } else {
                                return '<input type="text" style="width:200px" value="enter your name here" />';
                            }
                        }
                    },
                    queue:{
                        title:'Queue',
                        width:'8%'
                    },
                    name:{
                        title:'Name',
                        width:'9%'
                    },
                    cpu_time:{
                        title:'Req. CPU time',
                        width:'14%',
//                        type:'date',
                        create:false,
                        edit:false
                    },
                    n_p:{
                        title:'N/P',
                        width:'3%'
                    },
                    queued:{
                        title:'Queued',
                        width:'14%'
                    },
                    started:{
                        title:'Started',
                        width:'14%'
                    },
                    running_time:{
                        title:'Running time',
                        width:'12%'
                    }
                }
            });

            $('#JobsContainer').jtable('load', {csrfmiddlewaretoken:"{{ csrf_token }}"});
        });
    </script>

    <div class="center">
        <br>

        <div id="JobsContainer"></div>
    </div>

{% endblock %}

templates/pytorque/stat.html
{% extends "pytorque/base.html" %}

{% load i18n %}

{% block title %}
    PyTorque statistics
{% endblock %}

{% block additionalHeadContent %}
    <script src="/media/js/highcharts.js" type="text/javascript"></script>
    <script src="/media/js/themes/chartit/gray.js" type="text/javascript"></script>

    {% load chartit %}
    {{ stat_charts|load_charts:"chart_container_time,chart_container_user" }}

    <script type="text/javascript">
        $(document).ready(function () {
            $.each(_chartit_hco_array, function (index, chartoptions) {
                chart = new Highcharts.Chart(chartoptions);
            });
        });
    </script>

{% endblock %}

{% block content %}
    <div class="center">
        <br>

        <div id='chart_container_time'> Chart will be rendered here</div>
        <div id='chart_container_user'> Chart will be rendered here</div>
    </div>
{% endblock %}

templates/pytorque/submit.html
{% extends "pytorque/base.html" %}

{% block title %}
    PyTorque submition
{% endblock %}

{% block content %}


    <div class="center">
        <form id="submitScriptForm" enctype="multipart/form-data" method="post"
              action="{{ "/user/"|add:userName|add:"/submit"}}">{% csrf_token %}
            {#        {{ form.as_p }}#}
            {#        <input id="djangoSubmit" type="submit" value="Submit"/>#}

            {{ form.non_field_errors }}


            <table id="sumbitScriptFormTable" cellspacing="0" cellpadding="4">

                <tr>
                    <td>
                        <div class="fieldWrapper">
                            <label for="id_jobName" class="H1">Job name:</label><br>
                            {{ form.jobName }}
                            {{ form.jobName.errors }}
                        </div>
                    </td>
                    <td>
                        <div class="fieldWrapper">
                            {{ form.executionCommands.errors }}
                            <label for="id_executionCommands" class="H1">Execution commands:</label><br>
                            {{ form.executionCommands }}
                        </div>
                    </td>
                </tr>


                <tr>
                    <td>
                        <label class="H1">Job Options</label>
                        <table class="jobOptionsTable" cellspacing="10">
                            <tr>
                                <td><label for="id_queueToSubmitJobTo" class="H2">Queue to submit job to:</label></td>
                                <td>{{ form.queueToSubmitJobTo }}</td>
                            </tr>
                            <tr>
                                <td class="empty"></td>
                                <td>{{ form.queueToSubmitJobTo.errors }}</td>
                            </tr>

                            <tr>
                                <td><label for="id_cpuToUse" class="H2">Number of processors to use:</label></td>
                                <td>{{ form.cpuToUse }}</td>
                            </tr>
                            <tr>
                                <td class="empty"></td>
                                <td>{{ form.cpuToUse.errors }}</td>
                            </tr>

                            <tr>
                                <td><label for="id_maxTime" class="H2">Maximum time (HH:MM:SS):</label></td>
                                <td>{{ form.maxTime }}</td>
                            </tr>
                            <tr>
                                <td class="empty"></td>
                                <td>{{ form.maxTime.errors }}</td>
                            </tr>

                            <tr>
                                <td><label class="H2">Send message when job:</label></td>
                                <td><label for="id_sendMessageAbort" class="H3">Aborts:</label>
                                    {{ form.sendMessageAbort }}
                                    <label for="id_sendMessageEnd" class="H3">Ends:</label>
                                    {{ form.sendMessageEnd }}
                                    <label for="id_sendMessageStart" class="H3">Starts:</label>
                                    {{ form.sendMessageStart }}
                                </td>
                            </tr>

                            <tr>
                                <td><label for="id_sendMessageTo" class="H2">Address to send message to:</label></td>
                                <td>{{ form.sendMessageTo }}</td>
                            </tr>
                            <tr>
                                <td class="empty"></td>
                                <td>{{ form.sendMessageTo.errors }}</td>
                            </tr>
                        </table>
                    </td>

                    <td>
                        <label class="H1">File Staging (data files only; executable automatically staged)</label>
                        <table class="fileStagingTable">
                            <tr>
                                <td colspan="2"><label class="H1">Stagein:</label></td>
                            </tr>

                            <tr>
                                <td><label for="id_stageInFrom" class="H2">From here:</label></td>
                                <td>{{ form.stageInFrom }}</td>
                            </tr>
                            <tr>
                                <td class="empty"></td>
                                <td>{{ form.stageInFrom.errors }}</td>
                            </tr>

                            <tr>
                                <td><label for="id_stageInTo" class="H2">To there:</label></td>
                                <td>{{ form.stageInTo }}</td>
                            </tr>
                            <tr>
                                <td class="empty"></td>
                                <td>{{ form.stageInTo.errors }}</td>
                            </tr>

                            <tr>
                                <td colspan="2"><label class="H1">Stageout:</label></td>
                            </tr>

                            <tr>
                                <td><label for="id_stageOutFrom" class="H2">From here:</label></td>
                                <td>{{ form.stageOutFrom }}</td>
                            </tr>
                            <tr>
                                <td class="empty"></td>
                                <td>{{ form.stageOutFrom.errors }}</td>
                            </tr>

                            <tr>
                                <td><label for="id_stageOutTo" class="H2">To there:</label></td>
                                <td>{{ form.stageOutTo }}</td>
                            </tr>
                            <tr>
                                <td class="empty"></td>
                                <td>{{ form.stageOutTo.errors }}</td>
                            </tr>
                        </table>

                    </td>
                </tr>
            </table>


            <p align="center"><input type="submit" value="Submit Script"/></p>

        </form>
    </div>

{% endblock %}

templates/pytorque/upload.html
{% extends "pytorque/base.html" %}

{% load i18n %}

{% block title %}
    PyTroque uploading
{% endblock %}


{% block content %}
    <div class="center upload">
        <p style="font-size: 28px;">Please, select file to upload:</p>

        <form id="fileForm" enctype="multipart/form-data" method="post"
              action={{ "/user/"|add:userName|add:"/browse/upload" }}>
            {% csrf_token %}
            {{ form.as_p }}
            <input id="djangoSubmit" type="submit" value="Submit"/>

            <input type="hidden" name="currentDirectory" value="{{ currentDirectory }}"/>
        </form>
    </div>
{% endblock %}